name: linters

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install node, eslint, html-lint
        run: |
          sudo apt update
          sudo apt install nodejs
          sudo apt install npm
          npm i -g html-lint
          npm i -g eslint
          npm install --save-dev eslint eslint-config-google

          
      - name: Run html-lint
        run: |
          html-lint index.html --strict --verbose

      - name: Run eslint
        run: |
          eslint -c .eslintrc.json app.js
